### ISSUE TITLE
GetUserAssignedIdentity worked in 2.63.0, errors in 2.64.1

### ISSUE THREAD

**Issue by smithrobs** [pulumi/pulumi-azure-native#3610]
### What happened?

Same repro program, tried with `pulumi` 3.134.1 and 3.135.0 with same results.

### Expected

Retrieval of identity with no error like 2.63.0 did.

### Actual

2.64.1 fails with an error:

```
    I1001 15:18:33.771128   72374 main.go:137] language host identified executor from path: `/opt/homebrew/bin/pulumi-language-python-exec`

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/./__main__.py", line 36, in <module>
        autoIdentity = managedidentity.get_user_assigned_identity_output(resource_group_name="shared-dev-aks-rg", resource_name="shared-dev-aks-identity50da53d1")
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/venv/lib/python3.9/site-packages/pulumi_azure_native/managedidentity/get_user_assigned_identity.py", line 195, in get_user_assigned_identity_output
        __ret__ = pulumi.runtime.invoke_output('azure-native:managedidentity:getUserAssignedIdentity', __args__, opts=opts, typ=GetUserAssignedIdentityResult)
    AttributeError: module 'pulumi.runtime' has no attribute 'invoke_output'
```

### Example

```python
import pulumi

from pulumi_azure_native import managedidentity

myIdentity = managedidentity.get_user_assigned_identity_output(resource_group_name="my-dev-aks-rg", resource_name="my-dev-aks-identity")

pulumi.export('autoIdentityId', autoIdentity.id)
```

### Output of `pulumi about`

```
CLI          
Version      3.135.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  aws           6.47.0
resource  azure-native  2.64.1
resource  command       1.0.1
resource  github        6.2.3
language  python        unknown
resource  random        4.16.3

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in python: executable='/Users/rsmith/Documents/scratch/aws-py-scratch/venv/bin/python' version='3.9.6'

Current Stack: rsmith-pulumi-corp/py-scratch/dev

TYPE                                 URN
pulumi:pulumi:Stack                  urn:pulumi:dev::py-scratch::pulumi:pulumi:Stack::py-scratch-dev
pulumi:providers:azure-native        urn:pulumi:dev::py-scratch::pulumi:providers:azure-native::default_2_64_1
pulumi:providers:azure-native        urn:pulumi:dev::py-scratch::pulumi:providers:azure-native::default_2_63_0
pulumi:providers:azure-native        urn:pulumi:dev::py-scratch::pulumi:providers:azure-native::default_2_62_0


Found no pending operations associated with dev

Backend        
Name           pulumi.com
...
Token type     personal

Dependencies:
NAME                 VERSION
debugpy              1.8.6
pip                  24.2
pulumi_aws           6.47.0
pulumi_azure_native  2.64.1
pulumi_command       1.0.1
pulumi_github        6.2.3
pulumi_random        4.16.3
PyNaCl               1.5.0
setuptools           75.1.0
wheel                0.44.0
```

### Additional context

Possibly related to https://github.com/pulumi/pulumi/pull/17275 ?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
