### ISSUE TITLE
AttributeError when calling network.get_public_ip_address

### ISSUE THREAD

**Issue by AdityaGudimella** [pulumi/pulumi-azure-native#1945]
### What happened?

The following code:
```python
from pulumi_azure_native import network
...
output = pulumi.Output.all(vm_id, public_ip_name, resource_group_name)
public_ip_address = output.apply(lambda lst: network.get_public_ip_address(public_ip_address_name=lst[1], resource_group_name=lst[2])
```
raises the error:
```
pulumi_azure_native/network/get_public_ip_address.py", line 341, in get_public_ip_address
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
```

### Steps to reproduce

```python
from pulumi_azure_native import network
...
# vm_id is VirtualMachine.id, public_ip_name is PublicIPAddress.name and resource_group_name is str
output = pulumi.Output.all(vm_id, public_ip_name, resource_group_name)
public_ip_address = output.apply(lambda lst: network.get_public_ip_address(public_ip_address_name=lst[1], resource_group_name=lst[2])
```
The same code works in pulumi-azure-native 1.67.0, but doesn't work in 1.71.0. I haven't tried the versions in between.

### Expected Behavior

The same code that works in pulumi-azure-native 1.67.0 does not work in 1.71.0

### Actual Behavior

```
pulumi_azure_native/network/get_public_ip_address.py", line 341, in get_public_ip_address
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
``` 
is raised

### Output of `pulumi about`

CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/AdityaGudimella
User           AdityaGudimella
Organizations  AdityaGudimella

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the plugin: failed to load language plugin : no language plugin 'pulumi-language-' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install language `
warning: Failed to load language plugin : no language plugin 'pulumi-language-' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install language `
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from ). If you have not created a project yet, use `pulumi new` to do so

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi, what version of the `pulumi` package are you referencing in your dependencies?

When you're upgrading the `pulumi-azure-native` package, are you also upgrading the `pulumi` package too? The `InvokeOptions.merge()` method was added around 3 months ago so wouldn't exist if you only upgrade one package and not the other.

**Comment by danielrbradley** [comment]
Ok, I've confirmed that you need to upgrade your pulumi version to at least v3.35.0. I've added https://github.com/pulumi/pulumi-azure-native/issues/1947 to fix the dependency requirement.

**Comment by AdityaGudimella** [comment]
Hey,
Sorry for the late reply. Pulumi cli version is 3.38.0 as shown in my previous post. But I'm still getting this issue. Let me try updating to the latest version of pulumi and report back to you.

**Comment by danielrbradley** [comment]
Ah - this isn't the Pulumi CLI version, but the [`pulumi` PyPi package](https://pypi.org/project/pulumi/). The version range should be fixed in the next release which should be later today.
